version: "3.9"
services:
  django:
    build:
      context: ./django 
    container_name: django_app
    command: python manage.py runserver 0.0.0.0:8000 
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./django:/app

  db:
    image: postgres:16
    container_name: postgres_db 
    env_file: .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  nginx:
    image: nginx:latest 
    container_name: nginx 
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d 
    depends_on:
      - django 

volumes:
  pgdata: