controller:
  image:
    tag: "2.527-jdk17"
  admin:
    username: admin
    password: admin123

  serviceType: LoadBalancer
  servicePort: 80
  service:
    port: 80
    targetPort: 8080

  resources:
    limits:
      cpu: "500m"
      memory: "1Gi"
    requests:
      cpu: "250m"
      memory: "512Mi"

  persistentVolume:
    enabled: true
    storageClass: "ebs-sc"
    size: 10Gi

  containerEnv:
    - name: GITHUB_USER
      valueFrom: { secretKeyRef: { name: jenkins-shared, key: user } }
    - name: GITHUB_PAT
      valueFrom: { secretKeyRef: { name: jenkins-shared, key: pat } }
    - name: GITHUB_REPO_URL
      valueFrom: { secretKeyRef: { name: jenkins-shared, key: repo_url} }
      
  installPlugins:
    - kubernetes:latest
    - workflow-aggregator:latest
    - git:latest
    - configuration-as-code:latest
    - credentials-binding:latest
    - github:latest
    - docker-plugin:latest
    - docker-workflow:latest
    - job-dsl:latest

  serviceAccount:
     name: jenkins-sa
     create: false
  JCasC:
    configScripts:
      credentials: |
        credentials:
          system:
            domainCredentials:
              - credentials:
                  - usernamePassword:
                      scope: GLOBAL
                      id: github-token
                      username: ${GITHUB_USER}
                      password: ${GITHUB_PAT}
                      description: GitHub PAT
      seed-job: |
        jobs:
          - script: >
              job('seed-job') {
                description('Job to generate pipeline for Django project')
                scm {
                  git {
                    remote {
                      url('${GITHUB_REPO_URL}')
                      credentials('github-token')
                    }
                    branches('*/main')
                  }
                }
                steps {
                  dsl {
                    text('''
                      pipelineJob("goit-django-docker") {
                        definition {
                          cpsScm {
                            scm {
                              git {
                                remote {
                                  url("${GITHUB_REPO_URL}")
                                  credentials("github-token")
                                }
                                branches("*/main")
                              }
                            }
                          }
                        }
                      }
                    ''')
                  }
                }
              }