applications:
  - name: django-app
    namespace: default
    project: default
    source:
      repoURL: https://github.com/KryvkoSergii/goit-devops.git
      path: charts/django-app
      targetRevision: lesson-9
      helm:
        valueFiles:
          - values.yaml
    destination:
      server: https://kubernetes.default.svc
      namespace: default
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

# will create k8s secret with credentials to access private repo
# repositories:
#   - name: django-app
#     url: https://github.com/KryvkoSergii/goit-devops.git
#     username: YOUR_USERNAME
#     password: YOUR_PASS

repoConfig:
  insecure: "true"
  enableLfs: "true"